apiVersion: feed.workflow.summerwind.dev/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-release
spec:
  url: https://github.com/kubernetes/kubernetes/releases.atom
---
apiVersion: feed.workflow.summerwind.dev/v1alpha1
kind: Subscription
metadata:
  name: consul-release
spec:
  url: https://github.com/hashicorp/consul/releases.atom
---
apiVersion: feed.workflow.summerwind.dev/v1alpha1
kind: Subscription
metadata:
  name: vault-release
spec:
  url: https://github.com/hashicorp/vault/releases.atom
