apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: repository.github.workflow.summerwind.dev
spec:
  group: github.workflow.summerwind.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: Repository
    plural: repository
    singular: repository
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: issue.github.workflow.summerwind.dev
spec:
  group: github.workflow.summerwind.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: Issue
    plural: issue
    singular: issue
  scope: Namespaced
