apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: feed-controller
webhooks:
- name: subscription.feed.workflow.summerwind.dev
  clientConfig:
    caBundle: ""
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: slack-controller
webhooks:
- name: message.slack.workflow.summerwind.dev
  clientConfig:
    caBundle: ""
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: github-controller
webhooks:
- name: repository.github.workflow.summerwind.dev
  clientConfig:
    caBundle: ""
- name: issue.github.workflow.summerwind.dev
  clientConfig:
    caBundle: ""
